name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - '*.x'
      - task_wraps
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker images
    steps:
      - uses: actions/checkout@v4

      - name: Getting image tag
        if: github.repository == 'georchestra/gaia' && github.actor != 'dependabot[bot]'
        id: version
        run: echo "VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT

      - name: Build Celery image
        run: docker build -f docker/Dockerfile_celery -t georchestra/gaia-celery:${{ steps.version.outputs.VERSION }} .
      - name: Build Backend image
        run: docker build -f docker/Dockerfile_flask -t georchestra/gaia:${{ steps.version.outputs.VERSION }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: "Pushing latest to docker.io"
        run: |
          docker push georchestra/gaia-celery:${{ steps.version.outputs.VERSION }}
          docker push georchestra/gaia:${{ steps.version.outputs.VERSION }}

      - name: "Pushing branch/tag to docker.io"
        run: |
          docker tag georchestra/gaia-celery:latest georchestra/gaia-celery:${{ steps.version.outputs.VERSION }}
          docker tag georchestra/gaia:latest georchestra/gaia:${{ steps.version.outputs.VERSION }}
          docker push georchestra/gaia-celery:${{ steps.version.outputs.VERSION }}
          docker push georchestra/gaia:${{ steps.version.outputs.VERSION }}